name: event_bus_plus
description: Event Bus for Dart.
version: 0.6.2
homepage: https://github.com/AndrewPiterov/event_bus_plus

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies: 
  clock: ^1.1.2
  equatable: ^2.0.7
  logger: ^2.5.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^5.0.0
  given_when_then_unit_test: ^0.2.1
  shouldly: ^0.5.0+1
  test: ^1.25.9

